### ISSUE TITLE
Instructions for new raiders

### ISSUE THREAD

**Issue by Chefkeks** [pokepark/PokemonRaidBot#144]
New users welcome message: We could check if the user is already in the database and if it’s a new user, voting for the first time, we could send him info (which should be customizable) etc. along with maybe EU-GDPR agreement, which the bot misses too currently. Along with a \dsgvo or \eugdpr or \???? command to view and delete his data from the users table.

**Comment by Ninjasoturi** [comment]
This can be done with the tutorial mode in ninjasoturi_ingest branch. Telegram bots can't send private messages to users that haven't started the bot themselves first though.

**Comment by Artanicus** [comment]
Since this is available in the dev branch now I'll close this in anticipation of v3 going live to main.
