### ISSUE TITLE
History command

### ISSUE THREAD

**Issue by Chefkeks** [pokepark/PokemonRaidBot#179]
Would sometimes be nice to find out who signed up for a raid etc.without having to look into the database.

**Comment by Chefkeks** [comment]
Maybe /history, then select the gym, then the date, then show the raid poll as it was before it got deleted from Telegram

**Comment by Artanicus** [comment]
This might become more important with the new "auto-share on vote" feature since it only works if people don't abuse it, ergo if abusers are caught and punished swiftly.

**Comment by Ninjasoturi** [comment]
Added to ninjasoturi_ingest branch.

**Comment by Artanicus** [comment]
Since this is now in the dev branch and soon in main I'll close this as fixed!
