### ISSUE TITLE
Future Megas were Missing in Pokemon Table

### ISSUE THREAD

**Issue by quentar82** [pokepark/PokemonRaidBot#188]
Please update getDB.php with insertion of actual and future Mega Pokemon.

INSERT INTO pokemon (id, pokedex_id, pokemon_name, pokemon_form_name, pokemon_form_id, raid_level, min_cp, max_cp, min_weather_cp, max_weather_cp, weather, shiny, asset_suffix) VALUES
  (809, 18, 'Pidgeot', 'mega', -1, '0', 1151, 1216, 1439, 1521, 46, 0, '51'),
  (810, 65, 'Alakazam', 'mega', -1, '0', 1666, 1747, 2083, 2184, 6, 0, '51'),
  (811, 80, 'Slowbro', 'mega', -1, '0', 1382, 1454, 1728, 1817, 36, 0, '51'),
  (812, 94, 'Gengar', 'mega', -1, '0', 1566, 1644, 1958, 2055, 85, 0, '51'),
  (813, 115, 'Kangaskhan', 'mega', -1, '0', 1405, 1477, 1757, 1847, 4, 0, '51'),
  (814, 127, 'Pinsir', 'mega', -1, '0', 1613, 1690, 2016, 2113, 3, 0, '51'),
  (815, 130, 'Gyarados', 'mega', -1, '0', 1855, 1937, 2319, 2422, 36, 0, '51'),
  (816, 142, 'Aerodactyl', 'mega', -1, '0', 1515, 1590, 1894, 1988, 46, 0, '51'),
  (817, 150, 'Mewtwo', 'mega_x', -2, '0', 2294, 2387, 2868, 2984, 6, 0, '51'),
  (818, 150, 'Mewtwo', 'mega_y', -3, '0', 2294, 2387, 2868, 2984, 6, 0, '52'),
  (819, 181, 'Ampharos', 'mega', -1, '0', 1554, 1630, 1943, 2037, 3, 0, '51'),
  (820, 208, 'Steelix', 'mega', -1, '0', 1308, 1379, 1635, 1724, 712, 0, '51'),
  (821, 212, 'Scizor', 'mega', -1, '0', 1636, 1714, 2046, 2143, 37, 0, '51'),
  (822, 214, 'Heracross', 'mega', -1, '0', 1693, 1772, 2116, 2215, 35, 0, '51'),
  (823, 229, 'Houndoom', 'mega', -1, '0', 1432, 1505, 1790, 1882, 812, 0, '51'),
  (824, 248, 'Tyranitar', 'mega', -1, '0', 2103, 2191, 2629, 2739, 48, 0, '51'),
  (825, 254, 'Sceptile', 'mega', -1, '0', 1500, 1575, 1876, 1969, 12, 0, '51'),
  (826, 257, 'Blaziken', 'mega', -1, '0', 1550, 1627, 1938, 2034, 125, 0, '51'),
  (827, 260, 'Swampert', 'mega', -1, '0', 1622, 1699, 2027, 2124, 312, 0, '51'),
  (828, 282, 'Gardevoir', 'mega', -1, '0', 1688, 1767, 2110, 2209, 65, 0, '51'),
  (829, 302, 'Sableye', 'mega', -1, '0', 789, 843, 986, 1054, 8, 0, '51'),
  (830, 303, 'Mawile', 'mega', -1, '0', 877, 934, 1096, 1167, 75, 0, '51'),
  (831, 306, 'Aggron', 'mega', -1, '0', 1636, 1714, 2045, 2143, 74, 0, '51'),
  (832, 308, 'Medicham', 'mega', -1, '0', 764, 817, 955, 1022, 56, 0, '51'),
  (833, 310, 'Manectric', 'mega', -1, '0', 1267, 1337, 1585, 1672, 3, 0, '51'),
  (834, 319, 'Sharpedo', 'mega', -1, '0', 1174, 1246, 1468, 1558, 38, 0, '51'),
  (835, 323, 'Camerupt', 'mega', -1, '0', 1186, 1253, 1483, 1566, 12, 0, '51'),
  (836, 334, 'Altaria', 'mega', -1, '0', 1081, 1145, 1352, 1432, 6, 0, '51'),
  (837, 354, 'Banette', 'mega', -1, '0', 1244, 1313, 1555, 1642, 8, 0, '51'),
  (838, 359, 'Absol', 'mega', -1, '0', 1370, 1443, 1712, 1805, 8, 0, '51'),
  (839, 362, 'Glalie', 'mega', -1, '0', 1138, 1203, 1423, 1504, 7, 0, '51'),
  (840, 373, 'Salamence', 'mega', -1, '0', 2054, 2142, 2568, 2678, 6, 0, '51'),
  (841, 376, 'Metagross', 'mega', -1, '0', 2078, 2166, 2598, 2708, 76, 0, '51'),
  (842, 380, 'Latias', 'mega', -1, '0', 1921, 2066, 2402, 2507, 6, 0, '51'),
  (843, 381, 'Latios', 'mega', -1, '0', 2090, 2178, 2613, 2723, 6, 0, '51'),
  (844, 384, 'Rayquaza', 'mega', -1, '0', 2102, 2191, 2627, 2739, 6, 0, '51'),
  (845, 428, 'Lopunny', 'mega', -1, '0', 1112, 1177, 1391, 1471, 4, 0, '51'),
  (846, 445, 'Garchomp', 'mega', -1, '0', 2174, 2264, 2718, 2830, 612, 0, '51'),
  (847, 448, 'Lucario', 'mega', -1, '0', 1469, 1544, 1837, 1930, 57, 0, '51'),
  (848, 460, 'Abomasnow', 'mega', -1, '0', 1281, 1349, 1601, 1687, 127, 0, '51'),
  (849, 475, 'Gallade', 'mega', -1, '0', 1688, 1767, 2110, 2209, 65, 0, '51'),
  (850, 531, 'Audino', 'mega', -1, '0', 901, 961, 1127, 1201, 4, 0, '51');

**Comment by Artanicus** [comment]
To make this sustainable we need to generate the same dataset in `getDB.php`. It should be plausible;
- Keep a static list of known mega eligible mons
- For every mega eligible mon if no mega data is found in the gamemaster, generate a placeholder mega variant.
- Placeholder data being, form_name `mega`, form id `-1`, raid level `'0'`, CP data matching the normal form, asset_suffix `51`. The only exception is Mewtwo that has the X/Y split.

@Ninjasoturi am I missing anything?

**Comment by Ninjasoturi** [comment]
You're all good. I think there is no need to overcomplicate things. If you want to add stuff manually, just add them to ```$pokemon_array``` in ```getDB.php``` and you're all set. We already have all the data needed, so there is no need to hack the current parser logic to accommodate this.

**Comment by Artanicus** [comment]
The latest dev branch contains a feature to fetch new boss changes from /pokedex directly. They are available once the game master has them and it's been decoded & published.

So I'll close this in favor of allowing users to fetch new bosses whenever they become available.
