### ISSUE TITLE
Raid Overview doesn't contain level of egg

### ISSUE THREAD

**Issue by Artanicus** [pokepark/PokemonRaidBot#195]
The Raid Overview does say what the mon is if the egg has already opened but does not read what the level of an egg is if it's still an egg. This would be handy when a group contains say Tier 5 & Mega raids.

**Comment by Ninjasoturi** [comment]
@Artanicus Apparently there is a config option to enable pokemon/egg names in overview:
RAID_POLL_POKEMON_NAME_FIRST_LINE which is false by default.
