### ISSUE TITLE
pokedex_set_raid_level.php - Mega raid level missing

### ISSUE THREAD

**Issue by chrism431** [pokepark/PokemonRaidBot#259]
mods/pokedex_set_raid_level.php currently has:
`$raid_levels = [0,1,2,3,4,5,'X'];`

this leaves Mega raid level out, the (simple) fix, which also includes the abundant level 2 and 3 raid levels is:
`$raid_levels = [0,1,3,5,6,'X'];`

This offers all raid levels for manual addition of raid bosses.

**Comment by Ninjasoturi** [comment]
PR #260 fixes this. Already fixed in dev branch

**Comment by Artanicus** [comment]
Fix is in main.
