### ISSUE TITLE
Body Template System

### ISSUE THREAD

**Issue by florianbecker** [pokepark/PokemonRaidBot#26]
Create a system to use templates

Templates:
More relevant data first template
Current standard look
Minimal template

**Comment by Artanicus** [comment]
I know @Ninjasoturi has done a lot of customization of the body and I'd love to help him port some of that to the current HEAD. What kind of progress is there right now for templating the poll body?

**Comment by florianbecker** [comment]
None, only static configration variables:
  "RAID_POLL_UI_ORDER":"extra,teamlvl,time,pokemon,status",
  "RAID_POLL_HIDE_USERS_TIME":"10",
  "RAID_POLL_HIDE_BUTTONS_RAID_LEVEL":"1,2,3",
  "RAID_POLL_HIDE_BUTTONS_POKEMON":"",
  "RAID_POLL_HIDE_BUTTONS_TEAM_LVL":"true",
  "RAID_POLL_HIDE_DONE_CANCELED":"false",

**Comment by Artanicus** [comment]
So much has changed since this issue was filed that I'll close it as obsolete.
