### ISSUE TITLE
Add commands like /raidlevel5

### ISSUE THREAD

**Issue by Chefkeks** [pokepark/PokemonRaidBot#90]
Add commands like /raidlevel5 to allow quick updating of the raid bosses. Useful especially to enable/disable raid bosses at a specific time - think of scheduled telegram messages!

**Comment by Ninjasoturi** [comment]
Ninjasoturi_ingest branch supports raid boss scheduling, so I'd say once that get's merged to main, this feature isn't needed.

**Comment by Artanicus** [comment]
Since a superior feature is now in the dev branch and soon in main, this can be closed as fixed!
