### ISSUE TITLE
Pokebattler Import

### ISSUE THREAD

**Issue by Chefkeks** [pokepark/PokemonRaidBot#92]
- Add a command like /import with raid level, eg. `/import 3` to automatically import raid bosses. Telegram scheduled messages :D
- Allow import of level X raid bosses

**Comment by Ninjasoturi** [comment]
Ninjasoturi_ingest branch supports raid boss scheduling, so I'd say once that get's merged to main, this feature isn't needed.

**Comment by Artanicus** [comment]
Since this is obsolete in the dev branch I'll close this now to clean up old issues.
